[tool.poetry]
name = "hm-21-22"
version = "0.1.0"
description = ""
authors = ["pavel shevchenko <litvin.para@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
