# Generated by Django 5.0 on 2024-01-20 00:11

import ckeditor.fields
import hwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['mod_time']},
        ),
        migrations.AddField(
            model_name='note',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hwork.models.upload_to),
        ),
        migrations.AlterField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='max 255 symbols', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', to='hwork.tag', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='created_at_index'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['mod_time'], name='mod_time_index'),
        ),
    ]
