# Generated by Django 5.0 on 2023-12-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0002_alter_note_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
