# Generated by Django 5.0 on 2024-01-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0003_alter_note_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='created_at_index'),
        ),
    ]
