# Generated by Django 5.0 on 2024-01-06 13:18

import ckeditor.fields
import hwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0005_tag_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hwork.models.upload_to),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='max 255 symbols', max_length=255),
        ),
    ]
