# Generated by Django 5.0 on 2024-01-06 13:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0006_alter_note_content_alter_note_image_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержимое'),
        ),
    ]
