# Generated by Django 5.0 on 2024-01-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0008_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['mod_time'], name='mod_time_index'),
        ),
    ]
