# Generated by Django 5.0 on 2024-01-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0009_alter_note_mod_time_note_mod_time_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-mod_time']},
        ),
    ]
