# Generated by Django 5.0 on 2024-01-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0010_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['mod_time']},
        ),
    ]
