# Generated by Django 5.0 on 2024-01-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0012_note_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
